package_format_version = '1'
module_name = 'gnc_small_heritage'
module_version = '0.0.0'
min_geonature_version = '0.0.0'
max_geonature_version = '0.0.0'
exclude_geonature_versions = []
api_url='/small_heritage'